name: C/C++ CI

on:
  push:
    branches:
      - edge-private
      - p-[0-9]+-*
  # pull_request:
  #   branches:

jobs:
  checkout:
    name: checkout the repo with submodules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v1
      with:
        path: Motate/Tools/
        key: ${{ runner.os }}-tools-01 # Change the number to invalidate the tools caches

    - name: make CONFIG=Othermill
      run: make CONFIG=Othermill VERBOSE=2
      working-directory: ${{ github.workspace }}/g2core/

    - name: make CONFIG=OthermillPro
      run: make CONFIG=OthermillPro VERBOSE=2
      working-directory: ${{ github.workspace }}/g2core/
